### ISSUE TITLE
Please update HCP-diff train configs.

### ISSUE THREAD

**Issue by sashasubbbb** [cyber-meow/anime_screenshot_pipeline#29]
Hey, @cyber-meow! Can you please update hcp-diff training configs since tokenizers setup was changed, right now using you training preparation scripts i get missing key and missing tokenizer errors.
Thank you.

**Comment by cyber-meow** [comment]
Hi I think it still works unless there are new updates this week. I used it last weekend after updating hcp without problem.
There are now errors from create_embedding to make sure that the embedding name contains at least two tokens as otherwise it does not work correctly during training. Can you make sure your embedding names have indeed at least two tokens?

Edit: it seems that there are indeed some changes of hcp without backward compatiblility. I will add another version later.

**Comment by cyber-meow** [comment]
The configs are now updated.
Can be run with HCP commit 3663d975fc7e7cd94e1131c5eae2d74b0ac5256e
